#!/bin/bash

# Manual test script for Add Friend dialog
# This documents the test flow for UAT

echo "=== Add Friend Dialog Test Flow ==="
echo ""
echo "1. Start backend server:"
echo "   cd server && node index.js"
echo ""
echo "2. Start Electron app:"
echo "   npm start"
echo ""
echo "3. Login as ash_ketchum (password: pikachu123)"
echo ""
echo "4. Right-click context menu → Friends → Add Friend"
echo "   Expected: Dialog opens with search input focused"
echo ""
echo "5. Type 'prof' in search input"
echo "   Expected: After 300ms debounce, search results show 'prof_oak'"
echo ""
echo "6. Click 'Add Friend' button next to prof_oak"
echo "   Expected: Alert 'Friend request sent to prof_oak!', dialog closes"
echo ""
echo "7. Right-click → Friends → Add Friend again"
echo "   Search for 'misty'"
echo "   Click 'Add Friend' next to misty_cascade"
echo "   Expected: Alert 'Request already sent or you're already friends.' (ash and misty are already friends in seed data)"
echo ""
echo "8. Check browser DevTools console for logs:"
echo "   - [Friends] Opening Add Friend dialog"
echo "   - [Friends] Search: q=\"prof\", found 1 results"
echo "   - [Friends] Sending friend request to user X (prof_oak)"
echo "   - [Friends] Friend request sent successfully"
echo ""
echo "9. Check DevTools Network tab:"
echo "   - GET /api/users/search?q=prof (200 OK)"
echo "   - POST /api/friends/request (200 OK for prof_oak)"
echo "   - POST /api/friends/request (409 Conflict for misty_cascade)"
echo ""
echo "=== Verification Checklist ==="
echo "[ ] Dialog opens on menu click"
echo "[ ] Search input is focused"
echo "[ ] Typing triggers debounced search after 300ms"
echo "[ ] Search results render correctly"
echo "[ ] 'Add Friend' button sends POST /api/friends/request"
echo "[ ] Success shows alert and closes dialog"
echo "[ ] Duplicate request (409) shows appropriate error message"
echo "[ ] Console logs match expected pattern"
echo "[ ] Network tab shows correct API calls"
